[build]
  command = "npm ci && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[build.processing]
  skip_processing = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
